name: sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: collect lectures
      env:
        SEP_USER_NAME: ${{secrets.SEP_USER_NAME}}
        SEP_PASSWD: ${{secrets.SEP_PASSWD}}
        SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
        SENDER_PASSWD: ${{secrets.SENDER_PASSWD}}
        RECEIVER_EMAIL: ${{secrets.RECEIVER_EMAIL}}
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install requests lxml pillow
        python3 ./lecture.py
        bash .github/workflows/autocommit.sh
